#!/usr/bin/env bash
# transfers a file from my computee to a server via scp

if [ "$#" -lt 3 ]
then
	echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY";
elif [ "$#" -lt 4 ]
then
	scp -o StrictHostKeyChecking=no "$1" "$3@$2":~/
else
	scp -o StrictHostKeyChecking=no -i "$4" "$1" "$3@$2":~/
fi
ssh "$3@$2"
